// KB v3 Top-20 Entries — generated from factory gap analysis
// Generated: 2026-06-04
// Source: 84 gap-reports, 85 codebase files
// Action: merge into src/knowledge/pml-kb/*.ts

import type { KBEntry } from '../../src/knowledge/schemas/kb-entry';

export const kbV3Top20Entries: KBEntry[] = [
  // ═══════════ CRITICAL — from gap analysis ═══════════

  {
    id: 'cf_do_indices_loop',
    category: 'controlflow',
    subcategory: 'iteration',
    title: 'DO !var INDICES !array — index-based iteration',
    principle: 'DO с INDICES итерирует по индексам массива (1..N), что позволяет обращаться к элементам по позиции и использовать индекс для связных массивов.',
    rule: 'Используйте `do !i indices !array` когда нужен числовой индекс для доступа к нескольким связным массивам или для вывода номера итерации.',
    syntax: 'do !i indices !array\n  !item = !array[!i]\n  -- ...\nenddo',
    exampleCanonical: '-- CB ramImportExcelElementLoader.pmlobj\ndo !index indices !masterList\n  !listDetails = !masterList[!index]\n  !excelClassName = !listDetails[1]\n  !excelAttributeDetails = !listDetails[2]\n  if(!index.gt(!onePercentValue)) then\n    !!displayProgress(!index, !masterList.size())\n  endif\nenddo',
    exampleAntipattern: '-- WRONG: using from 1 to !array.size() when indices does the same\ndo !i from 1 to !array.size()\n  !item = !array[!i]\nenddo\n-- Works but less idiomatic than do !i indices !array',
    pitfalls: ['INDICES returns REAL indices starting from 1', 'Safe on empty arrays — loop body never executes', 'Prefer VALUES when index not needed'],
    relatedIds: ['cf_do_enddo_loop', 'cf_break_skip', 'dt_array_declaration'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §6.3 (DO loops)',
    sourcecodebase: 'ramImportExcelElementLoader.pmlobj, jacUpdateTagName.pmlfnc',
  },
  {
    id: 'cf_do_values_loop',
    category: 'controlflow',
    subcategory: 'iteration',
    title: 'DO !var VALUES !array — value-based iteration',
    principle: 'DO с VALUES итерирует непосредственно по значениям массива, что короче и идиоматичнее когда индекс не нужен.',
    rule: 'Используйте `do !item values !array` когда работаете с каждым элементом напрямую без необходимости знать его позицию.',
    syntax: 'do !item values !array\n  -- работа с !item напрямую\nenddo',
    exampleCanonical: '-- CB TagManagementTmp.pmlobj\ndo !tag values !tags\n  !tagRef = !tag.dbref()\n  !tagRef.:TagStatus = |VOID|\nenddo',
    exampleAntipattern: '-- WRONG: using indices just to get values\ndo !i indices !array\n  !item = !array[!i]  -- unnecessary index lookup\nenddo',
    pitfalls: ['VALUES gives the element directly, not a copy — modifications may affect original for objects', 'Cannot access index inside the loop body', 'Safe on empty arrays'],
    relatedIds: ['cf_do_indices_loop', 'cf_do_enddo_loop'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §6.3 (DO loops)',
    sourcecodebase: 'TagManagementTmp.pmlobj, jacPropagateParentData.pmlfnc',
  },
  {
    id: 'eh_specific_codes',
    category: 'errorhandling',
    subcategory: 'codes',
    title: 'HANDLE(group,code) — specific error code handling',
    principle: 'PML позволяет ловить конкретные коды ошибок через handle(group,code) вместо handle ANY, что даёт разную обработку для разных ошибок: (41,12)=duplicate name, (61,528)=Esc, (2,752)=PDMS-specific.',
    rule: 'Используйте handle(group,code) когда нужна разная реакция на разные ошибки. Комбинируйте с elsehandle для каскадной обработки. handle ANY — только когда любая ошибка обрабатывается одинаково.',
    syntax: 'handle (41,12)\n  -- duplicate name\nelsehandle (2,107)\n  -- element not found\nelsehandle none\n  -- no error\nendhandle',
    exampleCanonical: '-- CB TagManagementTmp.pmlobj (.getPipesBySuppoRef)\nvar !pipeName PIPE of $!pcomName\nhandle none\n  !pipeRef = !pipeName.dbref()\nelsehandle (2,111)\n  !result.appendArray(!this.getPipesBySuppoRef(!result, !pcomRef))\nelsehandle (2,115)\n  !msg = |REFNO $!pcomName is Nullref|\n  !this.errorList.append(!msg.split(|;|))\nendhandle',
    exampleAntipattern: '-- WRONG: using handle ANY when specific handling needed\nNEW EQUI /Name\nhandle any\nendhandle\n-- Swallows ALL errors including critical ones',
    pitfalls: ['Error codes not centrally documented — use show !!messagelist', 'handle(g,c) catches ONLY that code, others propagate', 'elsehandle none = code runs when NO error occurred'],
    relatedIds: ['eh_handle_endhandle', 'eh_handle_any', 'eh_nested_handle'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §8.2 (handle with error codes)',
    sourcecodebase: 'TagManagementTmp.pmlobj, createObjectsFromExcelSheet.pmlfnc',
  },
  {
    id: 'dn_netgridcontrol_excel',
    category: 'dotnetinterop',
    subcategory: 'excel',
    title: 'NETGRIDCONTROL + NETDATASOURCE — Excel I/O',
    principle: 'NETGRIDCONTROL и NETDATASOURCE — основной паттерн чтения/записи Excel в production PML. Чтение: NETDATASOURCE(title,path)→bind→getrows/gettitles. Запись: NETDATASOURCE(title,headers,data)→bind→saveGridToExcel.',
    rule: 'import GridControl с handle; для чтения: NETDATASOURCE(title, !path); для записи: NETDATASOURCE(title, !headers, !data) + .saveGridToExcel(!outputPath, !sheetName). Всегда clearGrid() перед re-bind.',
    syntax: "import 'GridControl'\nhandle any\nendhandle\n!grid = object NETGRIDCONTROL()\n!source = object NETDATASOURCE('data', !headers, !data)\n!grid.bindToDataSource(!source)\n!grid.saveGridToExcel(!path, |data|)",
    exampleCanonical: "-- CB JDE_tagProperties_export.pmlmac\n!dataTable = object NETGRIDCONTROL()\n!source = object NETDATASOURCE('data', !headerList, !dataList)\n!dataTable.BindToDataSource(!source)\n!dataTable.saveGridToExcel(|$!publishPath|, |data|)",
    exampleAntipattern: "-- WRONG: using NETGRIDCONTROL without import 'GridControl'\n!grid = object NETGRIDCONTROL()  -- Runtime error: type not found",
    pitfalls: ['NETDATASOURCE constructor differs for read vs write', 'Always clearGrid() before re-binding', 'saveGridToExcel takes path AND sheet name as two args', "import 'GridControl' with handle any is MANDATORY"],
    relatedIds: ['dn_import_guard', 'dn_excel_read_pattern', 'dn_file_write_pattern'],
    sourcedoc: 'TM-1402 PML Form Design Rev 1.0, §2.18 (.NET controls)',
    sourcecodebase: 'JDE_tagProperties_export.pmlmac, ramImportExcelProcessor.pmlfrm, ramCommonLogger.pmlobj',
  },
  {
    id: 'dt_array_core_methods',
    category: 'arrays',
    subcategory: 'methods',
    title: 'ARRAY core methods: append, size, clear, split',
    principle: 'ARRAY — основная коллекция PML. Ключевые методы: .append(!item) добавляет элемент, .size() возвращает длину, .clear() очищает, .split() создаёт массив из строки-разделителя, .appendArray(!other) объединяет два массива.',
    rule: 'Инициализируйте ARRAY перед append: !arr = object ARRAY(). Используйте .size() для проверки пустоты. .split() на строке создаёт массив по пробелам или указанному разделителю.',
    syntax: "!arr = object ARRAY()\n!arr.append('item1')\n!arr.appendArray(!other)\n!size = !arr.size()\n!arr.clear()\n!parts = !string.split('|;|')",
    exampleCanonical: "-- CB ramImportExcelElementLoader.pmlobj\n!reclassifyDetails = object ARRAY()\n!reclassifyDetails.append(!elementRefe)\n!reclassifyDetails.append(!className)\n!reclassifyDetails.append(!paramterDetails)\n!this.reclassifyMasterList.append(!reclassifyDetails)",
    exampleAntipattern: '-- WRONG: append on uninitialized variable\n!results.append(!item)  -- Error: !results is UNSET',
    pitfalls: ['Always initialize: !arr = object ARRAY() before append', 'PML arrays are 1-indexed, not 0-indexed', '.split() without args splits by whitespace', '.appendArray() merges, .append() adds as single element'],
    relatedIds: ['dt_array_declaration', 'cf_do_indices_loop', 'dt_array_advanced'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §5.6 (ARRAY)',
    sourcecodebase: 'ramImportExcelElementLoader.pmlobj, TagManagementTmp.pmlobj',
  },
  {
    id: 'pdms_dbref_badref_check',
    category: 'pdmsinteraction',
    subcategory: 'validation',
    title: 'DBREF validation: badref() + unset() before access',
    principle: 'Каждый DBREF из атрибута PDMS может быть невалидным (badref) или неинициализированным (unset). Доступ к свойствам без проверки вызывает runtime error. Паттерн: проверка .badref().not() перед доступом к .name/.acttype.',
    rule: 'Перед доступом к свойствам DBREF всегда проверяйте: !ref.badref().not() для ссылочных атрибутов, !ref.unset().not() для переменных. Для .dbRef() из строки — оборачивайте handle any.',
    syntax: 'if (!ref.badref().not()) then\n  !name = !ref.name\nendif\n-- или\n!ref = !name.dbRef()\nhandle any\nendhandle',
    exampleCanonical: "-- CB ramImportExcelElementLoader.pmlobj (.validateName)\n!elementRefe = !validName.dbRef()\nhandle any\nendhandle\nreturn !elementRefe\n\n-- CB jacPropagateParentData.pmlfnc\n!parentRef = !tagRef.attribute(!parentAttribute)\nif(!parentRef.badref().not()) then\n  do !attIdx indices !attList\n    !attValue = !parentRef.attribute(!attList[!attIdx])\n  enddo\nendif",
    exampleAntipattern: '-- WRONG: accessing DBREF property without check\n!parentRef = !tagRef.:TagRefToParentTag\n!parentName = !parentRef.namn  -- Error if badref!',
    pitfalls: ['badref() for refs from attributes, unset() for variables', '.dbRef() from string without / searches relative to CE', 'badref TRUE = deleted element or empty reference attribute'],
    relatedIds: ['dt_dbref_usage', 'dt_unset_handling', 'pdms_element_existence'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §5.9 (DBREF)',
    sourcecodebase: 'ramImportExcelElementLoader.pmlobj, jacPropagateParentData.pmlfnc, ramGetBackRef.pmlfnc',
  },

  // ═══════════ HIGH — from gap analysis ═══════════

  {
    id: 'pdms_attribute_object',
    category: 'pdmsinteraction',
    subcategory: 'metadata',
    title: 'object ATTRIBUTE — introspection of DB attributes',
    principle: 'object ATTRIBUTE(!name) позволяет проверить существование атрибута (.hash()≠0), его тип (.type()), имя (.name()). Критично для динамической работы с атрибутами когда имя приходит из конфигурации.',
    rule: 'Создайте object ATTRIBUTE(!name), проверьте .hash() eq 0 (не существует). Для PML1: VAR !data ATTDEF attName TYPE SIZE RPTX.',
    syntax: '!att = object ATTRIBUTE(!attName)\nif (!att.hash() neq 0) then\n  !type = !att.type()\nendif',
    exampleCanonical: "-- CB ramImportExcelElementLoader.pmlobj (.convertValue)\n!attribute = object ATTRIBUTE(!attributeName)\nif (!attribute.hash() eq 0) then\n  !isError = true\n  !msg = 'Attribute $!attributeName is not existing'\nendif\n!attributeType = !attribute.type()",
    exampleAntipattern: '-- WRONG: accessing attribute without existence check\n!value = !eleRef.attribute(!dynamicName)\n-- Error if attribute does not exist in schema',
    pitfalls: ['.hash() == 0 means attribute not registered', '.type() returns string: REAL, TEXT, REFERENCE, LOGICAL', 'ATTDEF returns numeric type codes (1=INT, 2=REAL, 5=REF)'],
    relatedIds: ['tc_db_to_pml_mapping', 'pdms_attribute_query'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §7.4',
    sourcecodebase: 'ramImportExcelElementLoader.pmlobj, TagManagementTmp.pmlobj, jacExportFullDataReport.pmlfnc',
  },
  {
    id: 'coll_block_evaluate',
    category: 'collections',
    subcategory: 'batch',
    title: 'BLOCK + evaluate() — batch computation on arrays',
    principle: 'object BLOCK(expression) создаёт шаблон вычисления с !evalIndex. !array.evaluate(!block) применяет его к каждому элементу — PML-аналог map(). Позволяет извлечь поле/атрибут из массива объектов одной строкой.',
    rule: "Создайте BLOCK с выражением, использующим !evalIndex. Вызовите !array.evaluate(!block). Результат — новый ARRAY.",
    syntax: "!block = object BLOCK('!array[!evalIndex].name')\n!names = !array.evaluate(!block)",
    exampleCanonical: "-- CB jacUpdateClassDetails.pmlfnc\n!shellClassTypes = !shellClassRefes.evaluate(object BLOCK(|!shellClassRefes[!evalIndex].attribute(':RDLDabaconExpression').upcase()|))",
    exampleAntipattern: '-- WRONG: manual loop when evaluate() does the same\n!names = object ARRAY()\ndo !i indices !refs\n  !names.append(!refs[!i].name)\nenddo',
    pitfalls: ['!evalIndex is a magic variable inside BLOCK', 'BLOCK expression is a string — syntax errors only at evaluate() time', 'Result is always ARRAY of STRING'],
    relatedIds: ['pdms_collection_object', 'dt_array_advanced', 'fnc_array_accumulator'],
    sourcedoc: 'TM-1401 PML Macros Rev 2.0, §2.8 (BLOCK object)',
    sourcecodebase: 'jacUpdateClassDetails.pmlfnc, jacExportFullDataReport.pmlfnc',
  },
  {
    id: 'coll_collection_expression',
    category: 'collections',
    subcategory: 'query',
    title: 'COLLECTION + EXPRESSION — PML2 OOP query',
    principle: 'PML2 COLLECTION — объектная альтернатива PML1 VAR COLL ALL. Возвращает DBREF[] (не STRING[]). Позволяет задать тип (.type()), фильтр (.filter(EXPRESSION)), scope (.addScope()).',
    rule: 'object COLLECTION() → .type(typeName) → .filter(object EXPRESSION(filterString)) → .results(). Для простых случаев: !!CollectAllFor(type, filter, scope).',
    syntax: "!coll = object COLLECTION()\n!coll.type('ENGITE')\n!coll.filter(object EXPRESSION(!filter))\n!tags = !coll.results()",
    exampleCanonical: "-- CB jacUpdateTagName.pmlfnc\n!collection = object COLLECTION()\n!collection.type('ENGITE')\nif(!filter.set() AND !filter.trim().neq('')) then\n  !expression = object EXPRESSION(!filter)\n  !collection.filter(!expression)\nendif\n!tags = !collection.results()",
    exampleAntipattern: "-- LESS OPTIMAL: PML1 approach returns STRING[] not DBREF[]\nVAR !items COLLECT ALL (ENGITE) FOR CE\n-- Each element is a string RefNo, not DBREF",
    pitfalls: ['COLLECTION.results() returns DBREF[] vs PML1 COLL returns STRING[]', 'EXPRESSION() can throw on invalid filter — wrap in handle', '!!CollectAllFor() is a wrapper around PML1 COLLECT'],
    relatedIds: ['pdms_attribute_query', 'cf_do_indices_loop', 'coll_block_evaluate'],
    sourcedoc: 'TM-1401 PML Macros Rev 2.0, §3.2 (COLLECTION object)',
    sourcecodebase: 'jacUpdateTagName.pmlfnc, jacDeleteUnnamed.pmlfnc, jacRemoveDocumentDuplicate.pmlfnc',
  },
  {
    id: 'dn_import_handle_guard',
    category: 'dotnetinterop',
    subcategory: 'import',
    title: 'import + handle ANY — mandatory .NET guard',
    principle: 'Каждый import .NET-сборки ОБЯЗАН быть обёрнут в handle any/endhandle. Без guard: при отсутствии DLL весь pmlobj/pmlfnc не загрузится. Это САМЫЙ ЧАСТЫЙ паттерн в codebase (присутствует во ВСЕХ 12 объектах).',
    rule: "import 'NamespaceOrAssembly' — ВСЕГДА с handle any/endhandle СРАЗУ после. Располагать в НАЧАЛЕ файла (до define object/function).",
    syntax: "import 'GridControl'\nhandle any\nendhandle",
    exampleCanonical: "-- CB ramExcelReaderClass.pmlobj (начало файла)\nimport 'RamAEPMLExcelReader'\nhandle any\nendhandle\n\ndefine object RAMEXCELREADERCLASS\n  -- ...",
    exampleAntipattern: "-- WRONG: import without handle\nimport 'GridControl'\ndefine object MYOBJ\n  -- If DLL missing, entire object fails to load!",
    pitfalls: ['Without handle, missing DLL prevents entire file from loading', 'Place import at TOP of file, before define', 'Each import needs its own handle block'],
    relatedIds: ['eh_import_protection', 'eh_handle_any', 'dn_object_instantiation'],
    sourcedoc: 'TM-1401 PML Macros Rev 2.0, §4.3 (.NET Interop)',
    sourcecodebase: 'ALL 12 .pmlobj files, jacEISDeliveryForm.pmlfrm, RAMBiReportExport.pmlfnc',
  },
  {
    id: 'eh_undefined_guard',
    category: 'errorhandling',
    subcategory: 'guard',
    title: 'undefined() guard for global objects',
    principle: 'Глобальные объекты (!!ramCommonLogger) могут не существовать если pipeline ещё не инициализирован. Паттерн undefined() guard проверяет существование и создаёт при необходимости — lazy initialization.',
    rule: 'Перед использованием !!globalObject проверяйте: if(undefined(!!obj)) then !!obj = object CLASS() endif. Размещайте в начале каждой функции/метода, использующей глобал.',
    syntax: 'if(undefined(!!ramCommonLogger)) then\n  !!ramCommonLogger = object RAMCOMMONLOGGER()\nendif',
    exampleCanonical: "-- CB ramImportExcelElementLoader.pmlobj (.addErrorToList)\nif(undefined(!!ramCommonLogger)) then\n  !!ramCommonLogger = object RAMCOMMONLOGGER()\nendif\n!errorList = object ARRAY()\n!errorList.append(!element)\n!!ramCommonLogger.addLogDetails(!this.objecttype(), !errorList, !severityLevel)",
    exampleAntipattern: '-- WRONG: using global without check\n!!ramCommonLogger.addLogDetails(...)  -- Error if logger not created yet',
    pitfalls: ['undefined() checks variable existence, not value', 'Different from .unset() which checks if value assigned', 'Pattern used in 11+ functions in codebase'],
    relatedIds: ['mac_global_variables', 'log_common_logger_api', 'nc_variable_naming'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §3.5 (Variable scope)',
    sourcecodebase: 'ramImportExcelElementLoader.pmlobj, jacUpdateTagName.pmlfnc, jacDeleteUnnamed.pmlfnc',
  },
  {
    id: 'obj_file_lifecycle',
    category: 'objects',
    subcategory: 'file',
    title: 'FILE object: exists → readFile → writeFile',
    principle: 'object FILE(!path) — PML-обёртка для файловых операций. Ключевой lifecycle: создать → .exists() проверка → .readFile() чтение ARRAY строк → .writeFile(mode, !array) запись. Mode: OVERWRITE/APPEND.',
    rule: "Создайте object FILE(!path). Проверьте .exists() перед чтением. Запись: .writeFile('APPEND', !dataArray) или .writeFile('OVERWRITE', !dataArray).",
    syntax: "!file = object FILE(!path)\nif (!file.exists()) then\n  !lines = !file.readFile()\nendif\n!file.writeFile('APPEND', !dataArray)",
    exampleCanonical: "-- CB ramFileWriterClass.pmlobj\n!file = object FILE(!path)\n!file.writeFile('OVERW', !textDataFormat)\n\n-- CB createObjectsFromExcelSheet.pmlfnc — guard clause\n!file = object FILE(!excelFullPath)\nif (!file.exists().not()) then\n  return !result  -- early return if file missing\nendif",
    exampleAntipattern: '-- WRONG: reading without exists() check\n!file = object FILE(!path)\n!data = !file.readFile()  -- Error if file not found',
    pitfalls: ["writeFile modes: 'WRITE', 'OVERWRITE', 'APPEND' (codebase uses 'OVERW')", 'readFile() returns ARRAY of STRING (one per line)', 'File path with spaces needs pipe-string: |path with spaces|'],
    relatedIds: ['dn_file_write_pattern', 'cf_guard_clause'],
    sourcedoc: 'TM-1402 Form Design Rev 1.0, §3.3 (FILE Object)',
    sourcecodebase: 'ramFileWriterClass.pmlobj, createObjectsFromExcelSheet.pmlfnc, TagManagementTmp.pmlobj',
  },
  {
    id: 'dt_matchwild',
    category: 'datatypes',
    subcategory: 'string',
    title: 'Matchwild — wildcard string matching',
    principle: 'Метод .Matchwild(pattern) проверяет строку по шаблону с * (любые символы). Возвращает BOOLEAN. Используется повсеместно для фильтрации элементов, проверки имён, поиска подстрок.',
    rule: "Используйте !string.Matchwild('*pattern*') для поиска подстроки. * = любая последовательность символов. Регистрозависимый — для нечувствительного сравнения предварительно .upcase() или .lowcase().",
    syntax: "if (!name.Matchwild('*JDA*')) then\n  -- name contains JDA\nendif",
    exampleCanonical: "-- CB TagManagementTmp.pmlobj (.pipeDataTransfer)\nif (!fromTagName.matchwild(|*JDA*|)) then\n  if (!fromTagName.matchwild(|*\"*|)) then\n    !shortName = part(!fromTagName, 3, |-|)\n    !fromTagRef = !this.getPipeByShortName(!shortName)\n  endif\nendif",
    exampleAntipattern: '-- WRONG: using .occurs() for simple containment check\nif (!name.occurs(|JDA|).gt(0)) then  -- works but Matchwild is cleaner',
    pitfalls: ['Matchwild is case-sensitive — use .upcase() first for case-insensitive', '* matches zero or more characters', 'No ? single-char wildcard in PML Matchwild'],
    relatedIds: ['dt_string_declaration', 'dt_string_substitution'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §5.2 (STRING methods)',
    sourcecodebase: 'TagManagementTmp.pmlobj, ramImportExcelElementLoader.pmlobj',
  },
  {
    id: 'mac_pml_reload_object',
    category: 'syscom',
    subcategory: 'reload',
    title: 'PML RELOAD OBJECT — hot-reload without rehash all',
    principle: 'PML RELOAD OBJECT CLASSNAME перезагружает один pmlobj без полного pml rehash all. Используется в начале pipeline-макросов для гарантии актуальной версии объекта.',
    rule: 'Перед использованием объекта в pipeline-макросе выполните PML RELOAD OBJECT CLASSNAME (UPPERCASE). Быстрее чем pml rehash all.',
    syntax: 'PML RELOAD OBJECT TAGMANAGEMENTTMP',
    exampleCanonical: "-- CB JDE_data-import.pmlmac\nPML RELOAD OBJECT TAGMANAGEMENTTMP\n\n!!createObjectsFromExcelSheet(...)",
    exampleAntipattern: '-- WRONG: modifying .pmlobj and using old cached version\n!obj = object MYCLASS()  -- Uses stale cached version',
    pitfalls: ['Class name must be UPPERCASE in RELOAD command', 'Only reloads one object — use pml rehash all for batch', 'Does not reload dependent objects — reload chain manually'],
    relatedIds: ['obj_namespace_loading', 'mac_pipeline_pattern'],
    sourcedoc: 'TM-1401 PML Macros Rev 2.0, §2.1 (pml rehash)',
    sourcecodebase: 'JDE_data-import.pmlmac',
  },

  // ═══════════ MEDIUM — from gap analysis ═══════════

  {
    id: 'dt_string_replace_trim',
    category: 'datatypes',
    subcategory: 'string',
    title: 'STRING methods: Replace, Trim, Split, Occurs',
    principle: 'STRING в PML имеет набор методов трансформации: .Replace(old,new), .Trim() (удаляет пробелы), .Split(sep) → ARRAY, .Occurs(sub) → REAL (число вхождений), .Substring(start,len), .Length().',
    rule: 'Используйте .Replace() для замены подстрок, .Trim() для очистки пробелов, .Split() для разбиения в массив. .eqNocase() для регистронезависимого сравнения.',
    syntax: "!result = !str.Replace('old', 'new')\n!clean = !str.Trim()\n!parts = !str.Split('|;|')\n!count = !str.Occurs('|;|')",
    exampleCanonical: "-- CB TagManagementTmp.pmlobj\n!combinedDesc = !combinedDesc.Trim().Replace(|  |, | |)\n\n-- CB ramValueConverter.pmlobj — Split for date parsing\n!dateParts = !valueString.split(!sep)",
    exampleAntipattern: '',
    pitfalls: ['Replace is case-sensitive', 'Split without args splits by whitespace', 'Occurs returns REAL count of non-overlapping matches'],
    relatedIds: ['dt_string_declaration', 'dt_matchwild', 'dt_string_substitution'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §5.2 (STRING methods)',
    sourcecodebase: 'TagManagementTmp.pmlobj, ramValueConverter.pmlobj',
  },
  {
    id: 'ui_fmsys_progress',
    category: 'ui',
    subcategory: 'progress',
    title: '!!FMSYS.setProgress — progress bar for long ops',
    principle: 'Длительные операции обязаны показывать прогресс. !!FMSYS.setProgress(0-100) показывает/скрывает прогресс-бар. !!FMSYS.setProgressText() задаёт текст. setProgress(0) скрывает бар.',
    rule: 'Перед циклом: setProgress(0). Внутри: вычислить процент, вызвать setProgress. После: setProgress(0). Не вызывайте при каждой итерации — используйте guard.',
    syntax: "!!FMSYS.setProgress(0)\ndo !i indices !items\n  !!displayProgress(!i, !items.size())\nenddo\n!!FMSYS.setProgress(0)",
    exampleCanonical: "-- CB ramImportExcelElementLoader.pmlobj\n!!displayProgress(1, 100)\ndo !index indices !masterList\n  if(!index.gt(!onePercentValue)) then\n    !!displayProgress(!index, !masterList.size())\n  endif\nenddo\n\n-- CB TagManagementTmp.pmlobj\n!!FMSYS.setProgressText(|Tag-doc links recovering from UDAs..|)",
    exampleAntipattern: '',
    pitfalls: ['setProgress(0) hides the bar — must call at end', 'Calling every iteration slows down — use threshold guard', 'setProgress accepts REAL 0-100'],
    relatedIds: ['cf_do_indices_loop', 'mac_pipeline_pattern'],
    sourcedoc: 'TM-1402 Form Design Rev 1.0, §2.19 (!!FMSYS)',
    sourcecodebase: 'ramImportExcelElementLoader.pmlobj, TagManagementTmp.pmlobj',
  },
  {
    id: 'mac_onerror_golabel',
    category: 'macros',
    subcategory: 'errorhandling',
    title: 'ONERROR GOLABEL /Error — global error handler',
    principle: 'ONERROR GOLABEL — PDMS-механизм глобального перехвата ошибок в макросах. При любой необработанной ошибке выполнение переходит к LABEL /Error. Обязательно SAVEWORK+UNCLAIM ALL в обработчике.',
    rule: 'В начале pipeline-макроса: ONERROR GOLABEL /Error. В конце: LABEL /Error → handle any → SAVEWORK → UNCLAIM ALL → export log → endhandle → FINISH.',
    syntax: 'ONERROR GOLABEL /Error\n-- ... pipeline ...\nLABEL /Error\nhandle any\n  SAVEWORK\n  UNCLAIM ALL\nendhandle\nFINISH',
    exampleCanonical: "-- CB JDE_routine-macro-run.pmlmac\nTAGS\nONERROR GOLABEL /Error\n!!ramCommonLogger = object RAMCOMMONLOGGER()\n$P --- START ---\n-- ... steps ...\nLABEL /Error\nhandle any\n  SAVEWORK\n  UNCLAIM ALL\n  !!ramCommonLogger.writeErrorDataToExcel(|...log.xlsx|, false)\nendhandle\nFINISH",
    exampleAntipattern: '-- WRONG: pipeline without ONERROR — unhandled error leaves claims\ndo !tag values !tags\n  !tagRef.:TagStatus = |ACTIVE|\nenddo\n-- If error occurs, claims are NOT released',
    pitfalls: ['ONERROR is PDMS mechanism, not PML handle', 'LABEL/GOLABEL work only within same file', 'FINISH is required to terminate macro cleanly'],
    relatedIds: ['cf_golabel_flow', 'pdms_transaction', 'ap_pipeline_macro'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §8 (ONERROR)',
    sourcecodebase: 'JDE_routine-macro-run.pmlmac',
  },
  {
    id: 'syscom_external_cmd',
    category: 'syscom',
    subcategory: 'external',
    title: 'SYSCOM — execute OS commands from PML',
    principle: 'SYSCOM запускает внешнюю команду ОС из PML. Используется для: открытия файлов/папок, конвертации, запуска утилит. Блокирует PML до завершения — для фоновых процессов добавьте &.',
    rule: "SYSCOM |command with $!variables|. Пути с пробелами — в двойных кавычках. Для фоновых: SYSCOM |cmd /C command &|.",
    syntax: 'SYSCOM |explorer /root, "$!logFilePath"|\nSYSCOM |CMD /C $!converter "$!file" &|',
    exampleCanonical: "-- CB TagManagementTmp.pmlobj (.SaveLog — opens folder)\nSYSCOM 'explorer /root, \"$!<this.pathName>\"'",
    exampleAntipattern: '',
    pitfalls: ['SYSCOM blocks until command completes — add & for background', 'Paths with spaces need double quotes inside |...|', 'SYSCOM does not return output — write to temp file and read'],
    relatedIds: ['mac_output_control', 'dn_file_write_pattern'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §9.3 (SYSCOM)',
    sourcecodebase: 'TagManagementTmp.pmlobj',
  },
  {
    id: 'dt_datetime_methods',
    category: 'datetime',
    subcategory: 'methods',
    title: 'DATETIME object — creation and formatting',
    principle: "object DATETIME() создаёт текущую дату/время. Методы .year()/.month()/.date()/.hour()/.minute() возвращают REAL-компоненты. Форматирование через .string('I2') для двузначных чисел.",
    rule: "Текущее время: !dt = OBJECT DATETIME(). Конкретная дата: object DATETIME(year,month,day,h,m,s). Форматирование: .month().string('I2').",
    syntax: "!dt = OBJECT DATETIME()\n!year = !dt.year()\n!month = !dt.month().string('I2')\n!date = !dt.date().string('I2')",
    exampleCanonical: "-- CB JDE_routine-macro-run.pmlmac\n!dt = OBJECT DATETIME()\n!year = !dt.year()\n!month = !dt.month().string('I2')\n!date = !dt.date().string('I2')\n!hour = !dt.hour().string('I2')",
    exampleAntipattern: '',
    pitfalls: ["Constructor: (year, month, day, hour, min, sec) — year first", "DATETIME() without args = current time", "'I2' format gives two-digit integer with leading zero"],
    relatedIds: ['tc_real_to_string', 'mac_file_path_pattern'],
    sourcedoc: 'TM-1401 PML Basic Rev 3.0, §5.8 (DATETIME)',
    sourcecodebase: 'JDE_routine-macro-run.pmlmac, JDE_tagProperties_export.pmlmac',
  },
];
