/** KB patch generated by pml-worker for mac_24 (JDE_fullDataProperties-export.pmlmac) */

import { KBEntry, KBCategory, normalizeCategory } from '../../../src/knowledge/schemas/kb-entry';

export const kbEntries_mac_24: KBEntry[] = [
  {
    id: 'datetime_object_methods',
    category: normalizeCategory('datetime'),
    subcategory: 'system_objects',
    title: 'DATETIME system object — year(), month(), date(), hour(), minute() methods',
    principle: 'The DATETIME object provides date/time component extraction via method calls on an OBJECT DATETIME() instance.',
    rule: "Always create via OBJECT DATETIME(), then chain component methods. Use .string('I2') for zero-padded 2-digit formatting.",
    syntax: "!dt = OBJECT DATETIME()\n!year = !dt.year()\n!month = !dt.month().string('I2')",
    exampleCanonical: `-- CB JDE_fullDataProperties-export.pmlmac
!dt = OBJECT DATETIME()
!year = !dt.year()
!month = !dt.month().string('I2')
!date = !dt.date().string('I2')
!hour = !dt.hour().string('I2')
!minute = !dt.minute().string('I2')`,
    exampleAntipattern: '',
    pitfalls: [
      "DATETIME object not documented in official KB. Methods must be confirmed against AVEVA docs or real source.",
      ".string('I2') format specifier not in official syntax reference but confirmed in codebase.",
    ],
    relatedIds: ['string_object_methods', 'variable_interpolation_dollar'],
    sourcedoc: 'AVEVA PML Customization — System Objects',
    sourcecodebase: 'JDE_fullDataProperties-export.pmlmac',
  },
  {
    id: 'variable_interpolation_dollar',
    category: normalizeCategory('datatypes'),
    subcategory: 'string',
    title: '$!<var> variable interpolation in pipe-delimited strings',
    principle: 'PML supports $!<variable> syntax for interpolating local/global variable values into pipe-delimited strings at macro execution time.',
    rule: "Use $!<varname> inside |...| strings to embed variable values. For attribute references use $!/attribute.",
    syntax: "!publishPath = |C:\\path\\file_$!<year>-$!<month>-$!<date>.xlsx|",
    exampleCanonical: `-- CB JDE_fullDataProperties-export.pmlmac
!publishPath = |C:\\...\\TagPropertyValue_full_extract_$!<year>-$!<month>-$!<date>-$!<hour>.xlsx|
-- CB LoopData.pmlobj
!logFile = |$!<this.pathName>\\$!logName|`,
    exampleAntipattern: '',
    pitfalls: [
      "$!<var> vs $!var: angle brackets are used for local variables in some contexts; $!name per syntax reference is for command substitution.",
      "Mixing $!<var> and $!name in the same string is valid but may cause confusion.",
    ],
    relatedIds: ['datetime_object_methods', 'pipe_delimited_strings'],
    sourcedoc: 'AVEVA PML Syntax — Dollar special symbols',
    sourcecodebase: 'JDE_fullDataProperties-export.pmlmac',
  },
  {
    id: 'macro_metadata_comment_dollar_m',
    category: normalizeCategory('macros'),
    subcategory: 'metadata',
    title: '--$m macro metadata comment — source path tracking',
    principle: 'The --$m comment on line 1 of a macro file records the full source path of the macro, typically for development tracking and debugging.',
    rule: 'Place --$m with the full quoted path as the first line of any macro file. This is a comment, not an executable directive.',
    syntax: '--$m "C:\\path\\to\\macro.pmlmac"',
    exampleCanonical: `-- CB JDE_fullDataProperties-export.pmlmac
--$m "C:\\Users\\ADZV\\OneDrive - Ramboll\\AVEVA_SERVER\\Addons\\PMLLIB\\RAM\\Engineering\\jackdow\\_publish\\macro\\JDE_fullDataProperties-export.pmlmac"`,
    exampleAntipattern: '$M "C:\\path\\to\\macro.pmlmac"',
    pitfalls: [
      "Do not confuse --$m (comment) with $M (macro execution command).",
      'The $M command executes a macro file; --$m is purely a metadata comment.',
    ],
    relatedIds: ['datetime_object_methods', 'variable_interpolation_dollar'],
    sourcedoc: 'AVEVA PML Syntax — Dollar special symbols',
    sourcecodebase: 'JDE_fullDataProperties-export.pmlmac',
  },
];
