import { KBEntry } from '../schemas/kb-entry';

export const mac_20_kb_patches: KBEntry[] = [
  {
    suggestedId: 'string_after_method',
    category: 'string_object',
    subcategory: 'string_manipulation',
    title: 'STRING .after() method for substring extraction',
    principle: 'STRING objects provide .after() method to extract substring after a delimiter',
    rule: "!result = !str.after(|delimiter|) returns the portion of string after the first occurrence of delimiter",
    syntax: '!result = !stringVar.after(|delimiter|)',
    exampleCanonical: '-- CB mac_20\n!name = |/RAM/MyView|\n!afterSlash = !name.after(|/|)\n$P Result: $!afterSlash',
    exampleAntipattern: '!afterSlash = !name.substring(|/|)  -- not valid PML',
    pitfalls: [
      'Returns empty string if delimiter not found',
      'Case-sensitive delimiter matching',
    ],
    relatedIds: ['string_object_methods', 'string_replace_method'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
  {
    suggestedId: 'delete_member_mem_command',
    category: 'database_commands',
    subcategory: 'element_manipulation',
    title: 'DELETE member MEM command with dollar substitution',
    principle: 'DELETE $!<member>.type MEM removes all members of a specified type',
    rule: 'DELETE $!<obj>.type MEM deletes all elements/members of the type specified by the dollar-substituted member',
    syntax: 'DELETE $!<objectVar>.memberType MEM',
    exampleCanonical: '-- CB mac_20\n!dbViewGroup = /RAM_IM_DBViewGroup\nDELETE $!<dbViewGroup.type> MEM',
    exampleAntipattern: 'DELETE !dbViewGroup.type MEM  -- missing $ prefix for substitution',
    pitfalls: [
      '$! required for variable substitution in command context',
      'MEM keyword required',
    ],
    relatedIds: ['dollar_substitution_syntax', 'database_view_commands'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
  {
    suggestedId: 'handle_tuple_error_codes',
    category: 'error_handling',
    subcategory: 'specific_error_codes',
    title: 'Handle specific numeric error code tuples',
    principle: 'PML allows handling specific error code tuples (major, minor) with handle (major,minor)',
    rule: 'handle (major,minor) catches only that specific error combination; multiple elsehandle tuples can be chained',
    syntax: 'handle (majorCode,minorCode)\n  -- error handler\nelsehandle (majorCode2,minorCode2)\n  -- alternative handler\nendhandle',
    exampleCanonical: '-- CB mac_20\nhandle (68,5)\n  $P ERROR: element exists in list\nelsehandle (99,532)\n  $P ERROR: element does not exist\nelsehandle (99,534)\n  $P ERROR: long name\nendhandle',
    exampleAntipattern: 'handle 68  -- incomplete error code, may not match',
    pitfalls: [
      'Error codes are (major, minor) tuple, not single number',
      'Order matters: first matching handler wins',
    ],
    relatedIds: ['handle_any_pattern', 'elsehandle_none_pattern'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
  {
    suggestedId: 'elsehandle_none_pattern',
    category: 'error_handling',
    subcategory: 'no_error_handler',
    title: 'elsehandle none for no-error branch',
    principle: 'elsehandle none explicitly handles the no-error path within a handle block',
    rule: 'elsehandle none executes when no error occurred; useful for conditional logic after error-prone operations',
    syntax: 'handle any\n  -- error recovery\nelsehandle none\n  -- no error occurred, original state preserved\nendhandle',
    exampleCanonical: '-- CB mac_20\nhandle any\n  DELETE ATTCOLUMN\n  NEW EXPCOLUMN\n  -- fallback creation\nelsehandle none\n  -- no error, keep original ATTCOLUMN\nendhandle',
    exampleAntipattern: 'elsehandle  -- missing none, may cause syntax error',
    pitfalls: [
      'elsehandle none is different from omitting elsehandle',
      'Semantically means no-error branch not catch-all',
    ],
    relatedIds: ['handle_any_pattern', 'handle_tuple_error_codes'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
  {
    suggestedId: 'netgridcontrol_core_presentation',
    category: 'net_addins',
    subcategory: 'grid_controls',
    title: 'NETGRIDCONTROL from Aveva.Core.Presentation',
    principle: 'NETGRIDCONTROL is a .NET add-in object for displaying tabular data in PML',
    rule: 'Import GridControl, use namespace Aveva.Core.Presentation, create object NETGRIDCONTROL(), use clearGrid(), bindToDataSource(), getrows()',
    syntax: "import 'GridControl'\nhandle any\nendhandle\nusing namespace |Aveva.Core.Presentation|\n!grid = object NETGRIDCONTROL()\n!grid.clearGrid()",
    exampleCanonical: "-- CB mac_20\nusing namespace |Aveva.Core.Presentation|\n!dataTable = object NETGRIDCONTROL()\n!dataTable.clearGrid()\n!dataSource = object NETDATASOURCE('Grid Table', !fileName)\n!dataTable.bindToDataSource(!dataSource)\n!data = !dataTable.getrows()",
    exampleAntipattern: "NETGRIDCONTROL  -- missing 'object' keyword and namespace",
    pitfalls: [
      "Requires 'import GridControl' before use",
      "Requires 'using namespace |Aveva.Core.Presentation|'",
      'NETDATASOURCE is a separate object',
    ],
    relatedIds: ['import_module_pattern', 'netdatasource_object'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
  {
    suggestedId: 'netdatasource_object',
    category: 'net_addins',
    subcategory: 'grid_controls',
    title: 'NETDATASOURCE for Excel/data binding',
    principle: 'NETDATASOURCE provides data source for NETGRIDCONTROL, can read from Excel files',
    rule: "object NETDATASOURCE('DataSourceName', filePath) binds external data to grid control",
    syntax: "!source = object NETDATASOURCE('name', !filePath)\n!grid.bindToDataSource(!source)\n!rows = !grid.getrows()",
    exampleCanonical: "-- CB mac_20\n!fileName = |C:\\data\\source.xlsx|\n!dataSource = object NETDATASOURCE('Grid Table', !fileName)\n!dataTable.bindToDataSource(!dataSource)\n!data = !dataTable.getrows()",
    exampleAntipattern: "NETDATASOURCE('name')  -- missing file path argument",
    pitfalls: [
      'Requires GridControl add-in loaded',
      'File path must be valid and accessible',
    ],
    relatedIds: ['netgridcontrol_core_presentation', 'do_values_iteration'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
  {
    suggestedId: 'dbview_creation_commands',
    category: 'database_objects',
    subcategory: 'dbview_lifecycle',
    title: 'DbView (DBVW) creation and configuration commands',
    principle: 'DbView objects are created with NEW DBVW, configured with DESC/UDNA/AUTCRE/ALWDEL/ELEL commands',
    rule: 'NEW DBVW → DESC → UDNA → AUTCRE → ALWDEL → ELEL REM ALL → configure sub-objects (EXPFIL/EXPCOL/ATTCOL)',
    syntax: '!dbView = !name.dbref()\nNEW DBVW $!name\nDESC |description|\nUDNA |udname|\nAUTCRE TRUE\nALWDEL TRUE\nELEL REM ALL',
    exampleCanonical: '-- CB mac_20\n!dbView = !dbViewName.dbref()\nhandle any\n  NEW DBVW $!dbViewName\n  !dbViewUdname = !dbViewDesc.replace(|-|, | |)\n  DESC |$!dbViewUdname|\n  UDNA |$!dbViewUdname|\n  AUTCRE TRUE\n  ALWDEL TRUE\n  ELEL REM ALL\n  !dbView = !!ce\nendhandle',
    exampleAntipattern: 'NEW DBVW !name  -- missing $ prefix for variable',
    pitfalls: [
      'Must use $! for variable substitution in command context',
      'AUTCRE/ALWDEL require TRUE/FALSE values',
      'ELEL REM ALL clears existing element list',
    ],
    relatedIds: ['dollar_substitution_syntax', 'dbview_sub_objects', 'string_replace_method'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
  {
    suggestedId: 'dbview_sub_objects',
    category: 'database_objects',
    subcategory: 'dbview_lifecycle',
    title: 'DbView sub-objects: EXPFILTER, EXPCOLUMN, ATTCOLUMN',
    principle: 'DbViews contain sub-objects for expressions, columns, and filters created with NEW commands',
    rule: 'NEW EXPFILTER → EXPRESSION → EXPTYPE; NEW EXPCOLUMN → DESC → UDNA → EXPRESSION → EXPTYPE → UTYP; NEW ATTCOLUMN → DESC → UDNA → DBATTRIBUTE',
    syntax: 'NEW EXPFILTER\nEXPRESSION |expr|\nEXPTYPE \'PML\'\n\nNEW EXPCOLUMN\nDESC |name|\nUDNA |udname|\nEXPRESSION |expr|\nEXPTYPE \'PML\'\nUTYP $!<dataType>\n\nNEW ATTCOLUMN\nDESC |name|\nUDNA |udname|\nDBATTRIBUTE $!<attr>',
    exampleCanonical: "-- CB mac_20\nNEW EXPCOLUMN\nDESC |$!<name>|\nUDNA |$!<name>|\nif (!value.matchwild(|*!*|)) then\n  !value = $!<value>\nendif\nEXPRESSION |$!<value>|\nEXPTYPE 'PML'\nUTYP $!<dataType>",
    exampleAntipattern: "EXPRESSION !value  -- missing $ prefix and | delimiters",
    pitfalls: [
      "EXPTYPE requires quoted string 'PML'",
      'UTYP requires $! substitution for data type variable',
      'DESC and UDNA require | pipe delimiters for strings',
    ],
    relatedIds: ['dbview_creation_commands', 'dollar_substitution_syntax'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
  {
    suggestedId: 'elel_add_commands',
    category: 'database_commands',
    subcategory: 'element_manipulation',
    title: 'ELEL ADD and ELEL REM commands for DbView element lists',
    principle: 'ELEL commands manipulate element lists within DbView objects',
    rule: '$!<viewName> ELEL ADD $!<element> adds an element; ELEL REM ALL removes all elements',
    syntax: '$!<viewName> ELEL ADD $!<element>\nELEL REM ALL',
    exampleCanonical: '-- CB mac_20\n$!<dbViewName> ELEL ADD $!<value>\nhandle (68,5)\n  $P ERROR ELE $!<value> IS EXIST IN ELELIST\nelsehandle (99,532)\n  $P ERROR ELE $!<value> IS NOT EXIST\nendhandle',
    exampleAntipattern: 'ELEL ADD !value  -- missing $ prefix and view context',
    pitfalls: [
      'Requires $!<viewName> prefix for context',
      'Error codes (68,5), (99,532), (99,534) are specific to ELEL operations',
    ],
    relatedIds: ['handle_tuple_error_codes', 'dbview_creation_commands'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
  {
    suggestedId: 'string_replace_method',
    category: 'string_object',
    subcategory: 'string_manipulation',
    title: 'STRING .replace() method for text substitution',
    principle: 'STRING objects provide .replace(old, new) method for text substitution',
    rule: "!result = !str.replace(|oldText|, |newText|) returns string with all occurrences of oldText replaced by newText",
    syntax: '!result = !stringVar.replace(|old|, |new|)',
    exampleCanonical: '-- CB mac_20\n!dbViewUdname = !dbViewDesc.replace(|-|, | |)\n$P Converted: $!dbViewUdname',
    exampleAntipattern: "!result = !str.replace('-',' ')  -- single quotes not valid PML pipe strings",
    pitfalls: [
      'Use | pipe delimiters for string arguments',
      'Replaces all occurrences, not just first',
    ],
    relatedIds: ['string_object_methods', 'string_after_method'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
  {
    suggestedId: 'utyp_command',
    category: 'database_commands',
    subcategory: 'dbview_lifecycle',
    title: "UTYP command for setting data type in DbView columns",
    principle: "UTYP command sets the data type for expression and attribute columns in DbView",
    rule: "UTYP $!<dataType> assigns the data type variable to the current column context",
    syntax: 'UTYP $!<dataTypeVar>',
    exampleCanonical: "-- CB mac_20\nNEW EXPCOLUMN\nDESC |$!<name>|\nUDNA |$!<name>|\nEXPRESSION |$!<value>|\nEXPTYPE 'PML'\nUTYP $!<dataType>",
    exampleAntipattern: 'UTYP !dataType  -- missing $ prefix for substitution',
    pitfalls: [
      'Requires $! variable substitution',
      "Must be used within EXPCOLUMN or ATTCOLUMN context",
    ],
    relatedIds: ['dbview_sub_objects', 'dollar_substitution_syntax'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
  {
    suggestedId: 'macro_data_driven_template_pattern',
    category: 'macro_patterns',
    subcategory: 'data_driven',
    title: 'Data-driven macro template pattern with multi-type dispatch',
    principle: 'Macros can drive behavior from Excel data by reading rows and dispatching on parameter type codes',
    rule: 'Read Excel via NETGRIDCONTROL/NETDATASOURCE → iterate rows → check parameterType field → execute corresponding command block',
    syntax: '!data = !dataTable.getrows()\ndo !row values !data\n  !param = !row[2]\n  if (!param eq |TYPE1|) then\n    -- type 1 processing\n  elseif (!param eq |TYPE2|) then\n    -- type 2 processing\n  endif\nenddo',
    exampleCanonical: '-- CB mac_20\ndo !row values !data\n  !parameterType = !row[2]\n  if (!parameterType eq |1_ELEL| and !dbView.set()) then\n    $!<dbViewName> ELEL ADD $!<value>\n  endif\n  if (!parameterType eq |2_EXPFIL| and !dbView.set()) then\n    NEW EXPFILTER\n    EXPRESSION |$!<value>|\n    EXPTYPE \'PML\'\n  endif\nenddo',
    exampleAntipattern: 'for !row in !data  -- not valid PML, use DO/ENDDO',
    pitfalls: [
      'Each conditional uses !dbView.set() to ensure context is set',
      'Parameter type codes are strings requiring | delimiters',
      'Multiple independent if blocks (not elseif) allow multiple actions per row',
    ],
    relatedIds: ['do_values_iteration', 'handle_tuple_error_codes'],
    sourcedoc: 'AVEVA E3D PML Documentation',
    sourcecodebase: 'JDE_dbView_creator.pmlmac',
  },
];
