/**
 * KB Patch for mac_13 — EBE_assetRegister_import.pmlmac
 * Generated by pml-worker | gap analysis review
 * Date: 2026-06-03
 */

import type { KBEntry } from '../../knowledge/schemas/kb-entry';

export const kbPatches: KBEntry[] = [
  {
    id: "pml_dotnet_netgridcontrol",
    category: "dotnetinterop",
    subcategory: "gridcontrol",
    title: "NETGRIDCONTROL and NETDATASOURCE for Excel/CSV data import",
    principle: "Use NETGRIDCONTROL with NETDATASOURCE to import spreadsheet data into PML macros. GridControl add-in must be imported before use.",
    rule: "Always import 'GridControl' with error handling before creating NETGRIDCONTROL instances.",
    syntax: `!grid = object NETGRIDCONTROL()
!source = object NETDATASOURCE('Grid Table', !filePath)
!grid.bindToDataSource(!source)
!rows = !grid.getrows()
!titles = !grid.gettitles()`,
    exampleCanonical: `-- Import Excel data into PML
import 'GridControl'
handle any
endhandle
using namespace |Aveva.Core.Presentation|
!dataTable = object NETGRIDCONTROL()
!dataSource = object NETDATASOURCE('Grid Table', !filePath)
!dataTable.bindToDataSource(!dataSource)
!data = !dataTable.getrows()
!heading = !dataTable.gettitles()`,
    exampleAntipattern: `!dataTable = object NETGRIDCONTROL()  -- GridControl not imported`,
    pitfalls: [
      "GridControl add-in must be installed and accessible in the AVEVA environment",
      "NETDATASource constructor varies by add-in version",
      "Aveva.Core.Presentation namespace required for NETGRIDCONTROL"
    ],
    relatedIds: ["pml_dotnet_gridcontrol_addin", "pml_string_findfirst"],
    sourcedoc: "NET Interfaces.md",
    sourcecodebase: "EBE_assetRegister_import.pmlmac",
    status: "draft"
  },
  {
    id: "pml_element_createelement",
    category: "pdmsinteraction",
    subcategory: "elementmanager",
    title: "CREATEELEMENT and ELEMENTTYPE for programmatic element creation",
    principle: "Use CREATEELEMENT to create new PDMS/E3D elements programmatically. Set the element type via ELEMENTTYPE or SetElementTypeByName before adding attributes and executing.",
    rule: "Always validate ELEMENTTYPE before calling SetElementTypeByName. Check GetErrors() after Execute().",
    syntax: `!elem = object CREATEELEMENT()
!etype = object ELEMENTTYPE('|<typeName>|')
if (!etype.valid()) then
  !elem.SetElementTypeByName('|<typeName>|')
  !elem.AddAttributeValue('|NAME|', !name)
  !elem.Execute()
  !errors = !elem.GetErrors()
endif`,
    exampleCanonical: `!elementNet = object CREATEELEMENT()
!etype = object ELEMENTTYPE('|$!<class>|)
if (!etype.valid()) then
  !elementNet.SetElementTypeByName('|$!<class>|')
  !elementNet.AddAttributeValue(|NAME|, !tagName)
  !elementNet.Execute()
  !errors = !elementNet.GetErrors()
  do !error values !errors
    !msg = |$!tag;$!error|
  enddo
endif`,
    exampleAntipattern: `!elem = object CREATEELEMENT()
!elem.AddAttributeValue('|NAME|', !name)
!elem.Execute()  -- No element type set`,
    pitfalls: [
      "ELEMENTTYPE must match a valid AVEVA class name",
      "SetElementTypeByName by string name is more forgiving than ELEMENTTYPE constructor",
      "GetErrors() returns an array that must be iterated"
    ],
    relatedIds: ["pml_element_dbref", "pml_attribute_object"],
    sourcedoc: "Aveva.Engineering.PMLElementManager namespace",
    sourcecodebase: "EBE_assetRegister_import.pmlmac",
    status: "draft"
  },
  {
    id: "pml_string_chained_methods",
    category: "pml2",
    subcategory: "string",
    title: "Chained STRING methods: replace().trim(), findfirst(), lowcase()",
    principle: "STRING objects support method chaining in PML2. Common patterns include replace().trim() for data cleaning and findfirst() for array searching.",
    rule: "Chain .replace().trim() for cleaning input strings. Use .findfirst() to search ARRAY of strings.",
    syntax: `!clean = !raw.replace(|search|, |replace|).trim()
!idx = !array.findfirst(|value|)
!lower = !text.lowcase()`,
    exampleCanonical: `!tag = !row[!nameId].replace(|-|, |-|).trim()
!class = !row[!classId].replace(|-|, |-|).trim()
!nameId = !heading.findfirst(|NAME|)
if (!class.lowcase() neq |unset|) then`,
    exampleAntipattern: `!tag = trim(!row[!nameId])  -- trim is method, not function`,
    pitfalls: [
      "findfirst returns an index value, not a boolean — use .set() to test validity",
      "replace takes two pipe-delimited strings: search pattern and replacement",
      "lowcase() returns a copy, does not modify in place"
    ],
    relatedIds: ["pml_string_object", "pml_array_findfirst"],
    sourcedoc: "string object.md, ARRAY object.md",
    sourcecodebase: "EBE_assetRegister_import.pmlmac",
    status: "draft"
  },
  {
    id: "pml_handle_nested_scoping",
    category: "pml2",
    subcategory: "error_handling",
    title: "Nested handle blocks and scoping in PML",
    principle: "PML handle blocks can be nested. Inner handle blocks take precedence for errors within their scope. elsehandle must match its corresponding handle.",
    rule: "Each handle must have a matching endhandle. Nested handles should be clearly indented. elsehandle none catches no errors (acts as pass-through).",
    syntax: `handle any
  -- operations that may fail
  handle any
    -- inner operations
  endhandle
elsehandle none
  -- inner failure recovery
endhandle
endhandle`,
    exampleCanonical: `handle any
  !elem = object CREATEELEMENT()
  if (!etype.valid()) then
    !elem.SetElementTypeByName('|TYPE|')
  else
    !msg = |Error: invalid type|
  endif
endhandle`,
    exampleAntipattern: `handle any
  !elem = object CREATEELEMENT()  -- missing endhandle
elsehandle any  -- orphaned elsehandle`,
    pitfalls: [
      "elsehandle none catches zero errors — it is not the same as elsehandle any",
      "Nested handle scoping can be confusing — prefer flattening when possible",
      "Using namespace inside handle block may not persist after handle ends"
    ],
    relatedIds: ["pml_syntax_handle", "pml_using_namespace"],
    sourcedoc: "PML1 Syntax.md, PML_LANGUAGE_VARIANTS.md",
    sourcecodebase: "EBE_assetRegister_import.pmlmac",
    status: "draft"
  },
  {
    id: "pml_macro_finish_directive",
    category: "macros",
    subcategory: "execution",
    title: "FINISH directive to terminate macro execution",
    principle: "FINISH is a macro directive that immediately terminates execution of the current macro. It is the equivalent of exit in a form context.",
    rule: "Use FINISH at the end of macros that have completed their work or encountered a fatal error.",
    syntax: `-- cleanup operations
!file.Close()
FINISH`,
    exampleCanonical: `!IssueFile.Close()
FINISH`,
    exampleAntipattern: `!IssueFile.Close()  -- macro continues executing after this`,
    pitfalls: [
      "FINISH terminates the entire macro, not just the current block",
      "Do not use FINISH in form methods — use RETURN or exit instead",
      "FINISH is macro-specific, not available in all PML contexts"
    ],
    relatedIds: ["pml_macro_file_close"],
    sourcedoc: "macros.md",
    sourcecodebase: "EBE_assetRegister_import.pmlmac",
    status: "draft"
  }
];
