/**
 * KB Patch for mac_47 — unnamed-tag-delete.pmlmac
 * Generated by pml-worker rerun on 2026-06-03
 *
 * Two new KBEntry candidates:
 *   1. cmd_pml_reload_object — PML RELOAD OBJECT command
 *   2. obj_tagmanagementtmp — TAGMANAGEMENTTMP customer object
 */

import { KBEntry, KBCategory } from "../../../../../src/knowledge/schemas/kb-entry";

export const mac_47_kb_patches: KBEntry[] = [
  {
    id: "cmd_pml_reload_object",
    category: "macros",
    subcategory: "reload",
    title: "PML RELOAD OBJECT command",
    principle:
      "PML RELOAD OBJECT reloads a previously compiled PML object into the current session, ensuring the latest definition is active.",
    rule:
      "Use PML RELOAD OBJECT <ObjectName> to reload an object after its source has been modified. The object must already exist in the session.",
    syntax: "PML RELOAD OBJECT <ObjectName>",
    exampleCanonical:
      "-- Reload TAGMANAGEMENTTMP before using it\nPML RELOAD OBJECT TAGMANAGEMENTTMP\n!tagMgmt = object TAGMANAGEMENTTMP()\n!tagMgmt.deleteUnnamedTags()",
    exampleAntipattern: "",
    pitfalls: [
      "Reloading a non-existent object will cause a runtime error",
      "Reloaded objects replace the previous instance in memory — existing references may become stale",
    ],
    relatedIds: ["cmd_pml_reload_macro", "obj_object_constructor"],
    sourcedoc: "AVEVA PML Customization Guide — Macros section",
    sourcecodebase: "unnamed-tag-delete.pmlmac",
  },
  {
    id: "obj_tagmanagementtmp",
    category: "objects",
    subcategory: "customer-specific",
    title: "TAGMANAGEMENTTMP customer object",
    principle:
      "TAGMANAGEMENTTMP is a project-specific PML object providing tag management utilities including deletion of unnamed tags.",
    rule:
      "Construct with object TAGMANAGEMENTTMP() and call deleteUnnamedTags() to remove unnamed tags from the current database context.",
    syntax: "!obj = object TAGMANAGEMENTTMP()\n!obj.deleteUnnamedTags()",
    exampleCanonical:
      "PML RELOAD OBJECT TAGMANAGEMENTTMP\n!tagMgmt = object TAGMANAGEMENTTMP()\n!tagMgmt.deleteUnnamedTags()",
    exampleAntipattern: "",
    pitfalls: [
      "Object must be reloaded after source changes",
      "deleteUnnamedTags() operates on the current database session context",
    ],
    relatedIds: ["cmd_pml_reload_object", "obj_object_constructor"],
    sourcedoc: "Customer codebase — unnamed-tag-delete.pmlmac",
    sourcecodebase: "unnamed-tag-delete.pmlmac",
  },
] as const;
