// KB Patch draft for mac_11 (class-name-refresh.pmlmac)
// Generated by pml-worker during factory rerun
// Review and apply to knowledge base as appropriate

interface KBEntry {
  id: string;
  category: string;
  subcategory: string;
  title: string;
  principle: string;
  rule: string;
  syntax: string;
  exampleCanonical: string;
  exampleAntipattern: string;
  pitfalls: string[];
  relatedIds: string[];
  sourcedoc: string;
  sourcecodebase: string;
}

const entries: KBEntry[] = [
  {
    id: "kb-tagmanagementtmp-object",
    category: "external_objects",
    subcategory: "pdms_addons",
    title: "TAGMANAGEMENTTMP Object",
    principle: "TAGMANAGEMENTTMP is a custom/external object used for tag management operations including alarm updates and class name updates.",
    rule: "Always PML RELOAD OBJECT before creating instances of TAGMANAGEMENTTMP to ensure latest method definitions are loaded.",
    syntax: `PML RELOAD OBJECT TAGMANAGEMENTTMP
!tagMgmt = object TAGMANAGEMENTTMP()
!tagMgmt.GetMappingData()
!tagMgmt.ClassNameUpdate(boolean)`,
    exampleCanonical: `PML RELOAD OBJECT TAGMANAGEMENTTMP
!tagMgmt = object TAGMANAGEMENTTMP()
!tagMgmt.GetMappingData()
!tagMgmt.ClassNameUpdate(true)`,
    exampleAntipattern: `!tagMgmt = object TAGMANAGEMENTTMP()  -- missing RELOAD OBJECT first
!tagMgmt.ClassNameUpdate(true)`,
    pitfalls: [
      "Skipping PML RELOAD OBJECT may cause stale method definitions.",
      "ClassNameUpdate expects a boolean argument; omitting it causes runtime error."
    ],
    relatedIds: ["kb-pml-reload-object-directive"],
    sourcedoc: "AVEVA PDMS/Plant Customization Guide",
    sourcecodebase: "class-name-refresh.pmlmac, alarm_refresh.pmlmac"
  },
  {
    id: "kb-pml-reload-object-directive",
    category: "directives",
    subcategory: "object_lifecycle",
    title: "PML RELOAD OBJECT Directive",
    principle: "PML RELOAD OBJECT reloads a PML object definition from its source, ensuring the latest version is available for instantiation.",
    rule: "Use PML RELOAD OBJECT before creating instances of custom or addon objects that may have been updated.",
    syntax: "PML RELOAD OBJECT <objectName>",
    exampleCanonical: "PML RELOAD OBJECT TAGMANAGEMENTTMP",
    exampleAntipattern: "",
    pitfalls: [
      "RELOAD OBJECT only affects objects loaded via PML; objects defined in .pmlobj files may need different reload mechanisms.",
      "Repeated reloads without cleanup may cause memory leaks for some object types."
    ],
    relatedIds: ["kb-tagmanagementtmp-object"],
    sourcedoc: "AVEVA PML Customization Guide",
    sourcecodebase: "class-name-refresh.pmlmac, alarm_refresh.pmlmac"
  }
];

export default entries;
