[
  {
    "suggestedId": "pml-builtin-undefined",
    "category": "builtin-functions",
    "subcategory": "variable-check",
    "title": "undefined() — Check if a global variable is uninitialized",
    "principle": "Use undefined() to safely check whether a global variable (prefixed with !!) has been assigned before use. Prevents BADREF errors on first access.",
    "rule": "Call undefined(!!globalVar) before accessing the variable. Returns BOOLEAN.",
    "syntax": "if(undefined(!!globalVar)) then\n  !!globalVar = object CUSTOMTYPE()\nendif",
    "exampleCanonical": "-- CB obj_06: lazy global initialization\nif(undefined(!!ramCommonLogger)) then\n  !!ramCommonLogger = object RAMCOMMONLOGGER()\nendif",
    "exampleAntipattern": "!!ramCommonLogger.addLogDetails(...) -- may throw BADREF on first call",
    "pitfalls": ["undefined() only works on global variables (!! prefix), not local variables"],
    "relatedIds": ["pml-builtin-error-text", "pml-object-initialization"],
    "sourcedoc": "obj_06 (ramImportExcelElementLoader.pmlobj)",
    "sourcecodebase": "ramImportExcelElementLoader.pmlobj"
  },
  {
    "suggestedId": "pml-builtin-error-text",
    "category": "builtin-functions",
    "subcategory": "error-handling",
    "title": "!!error.text — Global error message in handle/elsehandle",
    "principle": "Inside a handle/elsehandle block, !!error.text contains the human-readable error message from the last exception.",
    "rule": "Access !!error.text only inside handle or elsehandle blocks. Contains string description of the error.",
    "syntax": "handle any\n  !errorMsg = !!error.text\nelsehandle None\n  !result = !value\nendhandle",
    "exampleCanonical": "-- CB obj_06: error message capture\nhandle any\n  !this.addErrorToList(!element.name, !attribute, 'ER13 - ' + !!error.text + !additionalMessage)\nelsehandle None\n  !attributeType = !currentValue.objecttype()\nendhandle",
    "exampleAntipattern": "!msg = !!error.text -- outside handle block returns empty or undefined",
    "pitfalls": ["Only available inside handle/elsehandle blocks", "PML is case-insensitive but !!Error.text and !!error.text are the same"],
    "relatedIds": ["pml-control-handle", "pml-builtin-undefined"],
    "sourcedoc": "obj_06 (ramImportExcelElementLoader.pmlobj)",
    "sourcecodebase": "ramImportExcelElementLoader.pmlobj"
  },
  {
    "suggestedId": "pml-object-measure-format",
    "category": "system-objects",
    "subcategory": "unit-conversion",
    "title": "MEASURE and FORMAT objects — Unit conversion and formatting",
    "principle": "MEASURE wraps a unit string and provides dbunit() for database unit conversion. FORMAT controls numeric string output including units and trailing zeros.",
    "rule": "!measure = object MEASURE(!unitString)\n!dbUnit = !measure.dbunit()\n!format = object FORMAT()\n!format.units = !dbUnit.string()\n!format.TRAILZEROS = false",
    "syntax": "!measure = object MEASURE(!unit)\n!dbUnit = !measure.dbunit()\n!format = object FORMAT()\n!format.units = !dbUnit.string()\n!format.TRAILZEROS = false\n!result = !realValue.string(!format)",
    "exampleCanonical": "-- CB obj_06: unit conversion with formatting\n!measure = object MEASURE(!unit)\n!dbUnit = !measure.dbunit()\n!format = object FORMAT()\n!format.units = !dbUnit.string()\n!format.TRAILZEROS = false\n!realValue = object REAL(!tempValue)\n!result = !realValue.string(!format)",
    "exampleAntipattern": "!result = !tempValue -- loses unit information",
    "pitfalls": ["MEASURE requires a valid unit string", "FORMAT.TRAILZEROS controls trailing zero display"],
    "relatedIds": ["pml-object-real", "pml-string-methods"],
    "sourcedoc": "obj_06 (ramImportExcelElementLoader.pmlobj)",
    "sourcecodebase": "ramImportExcelElementLoader.pmlobj"
  },
  {
    "suggestedId": "pml-object-datetime-dateformat",
    "category": "system-objects",
    "subcategory": "datetime",
    "title": "DATETIME and DATEFORMAT objects — Timestamp generation",
    "principle": "DATETIME provides current date/time components. DATEFORMAT formats them into strings with configurable patterns.",
    "rule": "!time = object DATETIME()\n!dateFormat = object DATEFORMAT('Y_M_D')\n!dateStr = !dateFormat.string(!time)\n!fileName = !dateFormat.string(!time) + '_' + !time.hour().string() + ...",
    "syntax": "!time = object DATETIME()\n!dateFormat = object DATEFORMAT('Y_M_D')\n!dateStr = !dateFormat.string(!time)\n!fileName = !dateFormat.string(!time) + '_' + !time.hour().string() + !time.minute().string() + !time.second().string()",
    "exampleCanonical": "-- CB obj_06: timestamp-based filename\n!time = object DATETIME()\n!dateFormat = object DATEFORMAT('Y_M_D')\n!dateStr = !dateFormat.string(!time)\n!fileName = !dateFormat.string(!time) + '_' + !time.hour().string() + !time.minute().string() + !time.second().string()",
    "exampleAntipattern": "!fileName = !time.string() -- less control over format",
    "pitfalls": ["DATEFORMAT pattern uses Y_M_D not YYYY-MM-DD", "hour()/minute()/second() return numeric values requiring .string()"],
    "relatedIds": ["pml-object-measure-format", "pml-string-methods"],
    "sourcedoc": "obj_06 (ramImportExcelElementLoader.pmlobj)",
    "sourcecodebase": "ramImportExcelElementLoader.pmlobj"
  },
  {
    "suggestedId": "pml-control-skip-if",
    "category": "control-flow",
    "subcategory": "conditional-skip",
    "title": "skip if(condition) — Conditional early loop iteration",
    "principle": "skip if(condition) skips the current iteration when the condition is true. It is a compound form of the skip statement.",
    "rule": "skip if(!condition) — equivalent to 'if (!condition) then skip endif'",
    "syntax": "do !i indices !array\n  skip if(!isInvalid)\n  !result = !array[!i]\nenddo",
    "exampleCanonical": "-- CB obj_06: skip pseudo attributes and unmapped columns\nif(!isNameUpdate.not()) then\n  skip if(!isPseudo)\nendif\nskip if(!isMasterUnmapped)",
    "exampleAntipattern": "if(!isPseudo) then skip endif -- more verbose than skip if(!isPseudo)",
    "pitfalls": ["skip if() only works inside DO/ENDDO loops", "Condition must evaluate to BOOLEAN"],
    "relatedIds": ["pml-control-do-enddo", "pml-control-handle"],
    "sourcedoc": "obj_06 (ramImportExcelElementLoader.pmlobj)",
    "sourcecodebase": "ramImportExcelElementLoader.pmlobj"
  },
  {
    "suggestedId": "pml-statement-show",
    "category": "statements",
    "subcategory": "form-display",
    "title": "SHOW — Display a form by global reference",
    "principle": "SHOW statement displays a form identified by a global variable reference. Used to present user-facing dialogs from PML code.",
    "rule": "SHOW !!formGlobalVar — displays the form referenced by the global variable",
    "syntax": "SHOW !!ramimportExcelReclassificationForm\n!!ramimportExcelReclassificationForm.loadData(!this)",
    "exampleCanonical": "-- CB obj_06: show reclassification form\nSHOW !!ramimportExcelReclassificationForm\n!!ramimportExcelReclassificationForm.loadData(!this)",
    "exampleAntipattern": "show !localForm -- SHOW requires global variable reference",
    "pitfalls": ["SHOW requires a global (!!) form reference, not a local variable", "Form must be previously loaded/imported"],
    "relatedIds": ["pml-object-initialization", "pml-control-handle"],
    "sourcedoc": "obj_06 (ramImportExcelElementLoader.pmlobj)",
    "sourcecodebase": "ramImportExcelElementLoader.pmlobj"
  },
  {
    "suggestedId": "pml-builtin-display-progress",
    "category": "builtin-functions",
    "subcategory": "ui-feedback",
    "title": "displayProgress() — Show import progress bar",
    "principle": "displayProgress(current, total) displays a progress indicator in the AVEVA UI. Used for long-running import loops.",
    "rule": "Call with (current, total) parameters. PML is case-insensitive so !!displayProgress works.",
    "syntax": "!!displayProgress(1, 100)\ndo !i from 1 to !total\n  if(!i.gt(!onePercent)) then\n    !!displayProgress(!i, !total)\n  endif\nenddo",
    "exampleCanonical": "-- CB obj_06: progress tracking in import loop\n!!displayProgress(1, 100)\ndo !index indices !masterList\n  if(!index.gt(!onePercentValue)) then\n    !!displayProgress(!index, !masterList.size())\n  endif\nenddo",
    "exampleAntipattern": "!!displayProgress(!i) -- requires two parameters (current, total)",
    "pitfalls": ["Requires two parameters: current count and total", "Call sparingly to avoid UI flicker"],
    "relatedIds": ["pml-control-do-enddo", "pml-builtin-undefined"],
    "sourcedoc": "obj_06 (ramImportExcelElementLoader.pmlobj)",
    "sourcecodebase": "ramImportExcelElementLoader.pmlobj"
  }
]
