/**
 * KB Patch for obj_09 — jacEISDeliveryManager.pmlobj
 * Generated by pml-worker gap analysis.
 * Each entry is a KBEntry candidate for the PML knowledge base.
 */

import { KBEntry } from '../../../src/knowledge/schemas/kb-entry';

export const obj_09_kb_patches: KBEntry[] = [
  {
    id: 'kb_builtin_undefined',
    category: 'builtin_functions',
    subcategory: 'variable_introspection',
    title: 'undefined() function for global variable existence check',
    principle: 'Use undefined() to check if a global variable has been assigned before accessing it.',
    rule: 'undefined(!!globalVar) returns TRUE if the global is unassigned, FALSE if assigned.',
    syntax: 'if(undefined(!!globalVar)) then ... endif',
    exampleCanonical: `-- CB obj_09_addErrorToList
if(undefined(!!ramCommonLogger)) then
  !!ramCommonLogger = object RAMCOMMONLOGGER()
endif`,
    exampleAntipattern: `-- Accessing unassigned global without check
!!ramCommonLogger.addLogDetails(...) -- may crash if not initialized`,
    pitfalls: [
      'Only works with global variables (!!), not local variables (!)',
    ],
    relatedIds: ['kb_pml_variables'],
    sourcedoc: 'AVEVA PML Customization Guide',
    sourcecodebase: 'jacEISDeliveryManager.pmlobj',
  },
  {
    id: 'kb_string_unset',
    category: 'objects',
    subcategory: 'string_methods',
    title: 'STRING.unset() method for existence check',
    principle: 'Use unset() on STRING or ARRAY to check if the variable has been assigned a value.',
    rule: 'unset() returns TRUE if the variable is unassigned/undefined, FALSE if it holds a value.',
    syntax: `!str.unset() -- TRUE if !str is not set
!arr.unset() -- TRUE if !arr is not set`,
    exampleCanonical: `-- CB obj_09_loadReportDetails
if(!viewDetails.set() AND !viewDetails.size().eq(7)) then
  -- process details
else
  !this.clearData()
endif`,
    exampleAntipattern: `-- Checking set() vs unset() confusion
if(!str.unset()) then -- wrong: checks if unset, but code expects set
  ...`,
    pitfalls: [
      'set() and unset() are inverses: !x.set() is equivalent to !x.unset().not()',
    ],
    relatedIds: ['kb_string_methods', 'kb_array_methods'],
    sourcedoc: 'AVEVA PML Customization Guide',
    sourcecodebase: 'jacEISDeliveryManager.pmlobj',
  },
  {
    id: 'kb_object_objecttype',
    category: 'objects',
    subcategory: 'object_base_methods',
    title: 'OBJECT.objecttype() method for runtime type identification',
    principle: 'Use objecttype() on any PML2 object to get its type name as a STRING at runtime.',
    rule: 'objecttype() returns a STRING containing the object type identifier.',
    syntax: '!this.objecttype() -- returns the type name of the current object',
    exampleCanonical: `-- CB obj_09_addErrorToList
!!ramCommonLogger.addLogDetails(!this.objecttype(), !errorList)`,
    exampleAntipattern: `-- Hardcoding type names instead of using objecttype()
!!ramCommonLogger.addLogDetails('JACEISDELIVERYMANAGER', !errorList)`,
    pitfalls: [
      'Returns the declared type name, not the variable name',
    ],
    relatedIds: ['kb_pml2_objects'],
    sourcedoc: 'AVEVA PML Customization Guide',
    sourcecodebase: 'jacEISDeliveryManager.pmlobj',
  },
  {
    id: 'kb_block_avevalindex',
    category: 'constructs',
    subcategory: 'block_evaluation',
    title: 'BLOCK evaluate with !evalIndex special variable',
    principle: 'When evaluating a BLOCK on an ARRAY, !evalIndex is a special variable available inside the block that holds the current index.',
    rule: '!columns.evaluate(object BLOCK(|!columns[!evalIndex].string()|)) iterates over !columns, with !evalIndex set to each index.',
    syntax: '!array.evaluate(object BLOCK(|!array[!evalIndex].method()|))',
    exampleCanonical: `-- CB obj_09_columnCollection
!columnRefNos = !columns.evaluate(object BLOCK(|!columns[!evalIndex].string()|))
-- CB obj_09_loadReport
!headings = !headings.evaluate(object BLOCK(|!headings[!evalIndex][1]|))`,
    exampleAntipattern: `-- Using a regular loop instead of evaluate
DO !i FROM 1 TO !columns.Size()
  !result.Append(!columns[!i].string())
ENDDO`,
    pitfalls: [
      '!evalIndex is only available inside the BLOCK expression, not outside',
      'BLOCK evaluates each element; the result is an ARRAY of the evaluated values',
    ],
    relatedIds: ['kb_array_evaluate', 'kb_constructs_block'],
    sourcedoc: 'AVEVA PML Customization Guide',
    sourcecodebase: 'jacEISDeliveryManager.pmlobj',
  },
  {
    id: 'kb_pml1_project_code_evar',
    category: 'pml1_query',
    subcategory: 'system_variables',
    title: 'PROJECT CODE system variable with !!evar()',
    principle: 'PROJECT CODE is a PML1 system query variable that returns the current PDMS project code. Use !!evar() to evaluate it in PML2 context.',
    rule: '!!evar(|PDMSUSER|) returns the PDMS user data path. !!evar(!varName + |DFLTS|) returns the project defaults path.',
    syntax: `var !code PROJECT CODE
!!evar(!code + |DFLTS|)`,
    exampleCanonical: `-- CB obj_09_readConfiguration
!!filePath = !!evar(|PDMSUSER|) + |\\EISConfiguration.xlsx|
if(!file.exists().not()) then
  var !projectCode PROJECT CODE
  !filePath = !!evar(!projectCode + |DFLTS|) + |\\EISConfiguration.xlsx|
endif`,
    exampleAntipattern: `-- Using hardcoded paths instead of system variables
!filePath = 'C:\\project\\defaults\\config.xlsx'`,
    pitfalls: [
      'PROJECT CODE requires being in a PDMS session context',
      'DFLTS path depends on PDMS installation configuration',
    ],
    relatedIds: ['kb_pml1_query_system_vars'],
    sourcedoc: 'AVEVA PDMS Query Reference',
    sourcecodebase: 'jacEISDeliveryManager.pmlobj',
  },
];
